import { useState } from "react";
import { FiBell, FiCheck, FiLock, FiMapPin, FiUser } from "react-icons/fi";
import { useAuth } from "../Auth/AuthContext";

const Settings = () => {
  const { user } = useAuth();
  const [settings, setSettings] = useState(() => JSON.parse(localStorage.getItem("crime-alert-settings") || "null") || { alerts: true, location: true, anonymous: false });
  const [saved, setSaved] = useState(false);
  const update = (key) => setSettings((current) => ({ ...current, [key]: !current[key] }));
  const save = () => { localStorage.setItem("crime-alert-settings", JSON.stringify(settings)); setSaved(true); setTimeout(() => setSaved(false), 2000); };
  const options = [{ key: "alerts", icon: FiBell, title: "Safety notifications", description: "Get updates when reports near you are reviewed." }, { key: "location", icon: FiMapPin, title: "Location-aware feed", description: "Use your chosen area to prioritize nearby reports." }, { key: "anonymous", icon: FiLock, title: "Anonymous by default", description: "Hide your identity on newly created reports." }];
  return <main className="min-h-screen bg-[#f6f7f9] px-4 py-8 text-slate-900 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl"><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-red-600">Preferences</p><h1 className="text-4xl font-black tracking-tight text-slate-950">Settings</h1><p className="mt-2 text-sm text-slate-500">Control how Crime Alert keeps you informed.</p><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-4 border-b border-slate-100 p-6"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-red-50 text-red-600"><FiUser /></div><div><h2 className="font-bold text-slate-950">{user?.name || "Crime Alert member"}</h2><p className="text-sm text-slate-500">{user?.email || "Preview account"}</p></div></div><div className="divide-y divide-slate-100">{options.map(({ key, icon: Icon, title, description }) => <button type="button" key={key} onClick={() => update(key)} className="flex w-full items-center gap-4 p-6 text-left transition hover:bg-slate-50"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Icon /></span><span className="flex-1"><strong className="block text-sm text-slate-900">{title}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></span><span className={`flex h-6 w-10 items-center rounded-full p-1 transition ${settings[key] ? "bg-red-600 justify-end" : "bg-slate-200 justify-start"}`}><span className="h-4 w-4 rounded-full bg-white shadow" /></span></button>)}</div><div className="flex items-center justify-between border-t border-slate-100 p-6"><span className="text-xs text-emerald-600">{saved ? <span className="inline-flex items-center gap-1"><FiCheck /> Preferences saved</span> : "Changes stay on this device in preview mode."}</span><button onClick={save} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-red-600">Save settings</button></div></section></div></main>;
};

export default Settings;
